// nextjs/app/page.tsx
import { About } from "@/components/About";
import { Contact } from "@/components/Contact";
import { SkillList } from "@/components/SkillList";
import { TheTitle } from "@/components/TheTitle";

export default function Home() {
  return (
    <div id="root" className="text-base w-screen">
      <div className="mx-auto my-10 md:max-w-screen-md max-w-xs text-gray-600">
        <TheTitle className="mb-7" />
        <About className="mb-4" />
        <SkillList className="mb-4" />
        <Contact />
      </div>
    </div>
  );
}

// app.vue
<template>
  <div id="root" class="text-base">
    <div class="mx-40 my-10 text-gray-600">
      <TheTitle class="mb-7" />
      <About class="mb-4" />
      <SkillList class="mb-4" />
      <Contact />
    </div>
  </div>
</template>

<style lang="scss" scoped>
#root {
  border: 1px solid;
}
</style>
