// nextjs/components/Skills/Item.tsx
interface SkillItemProps {
  name: string;
  className?: string;
}

export function SkillItem({ name, className }: SkillItemProps) {
  return (
    <span
      className={`mr-2 px-3 py-1 border border-solid rounded-lg border-teal-500 text-teal-600 ${className || ""}`}
      style={{ fontFamily: '"Mulish", sans-serif' }}
    >
      {name}
    </span>
  );
}

// components/Skills/Item.vue
<template>
  <span
    class="
      mr-2
      px-3
      py-1
      border border-solid
      rounded-lg
      border-teal-500
      text-teal-600
    "
  >
    {{ name }}
  </span>
</template>

<script language="ts">
export default {
  props: {
    name: String,
  },
};
</script>

<style lang="scss" scoped>
span {
  font-family: "Mulish", sans-serif;
}
</style>
