// nextjs/components/About.tsx
interface AboutProps {
  className?: string;
}

export function About({ className }: AboutProps) {
  return (
    <div className={className}>
      <section>
        <h1 className="text-2xl uppercase">About me</h1>
        <div className="my-1">
          <p>
            I am Takahiro Hatanaka. I am working as a software engineer in Tokyo, Japan since 2011.
            I work mainly as a developer and sometime as a developer manager.
          </p>
        </div>
      </section>
    </div>
  );
}

// components/about.vue
<template>
  <section>
    <h1>About me</h1>
    <div>
      <p>
        I am Takahiro Hatanaka. I am working as a software engineer in Tokyo,
        Japan since 2011.
        <br />
        I work mainly as a developer and sometime as a developer manager.
      </p>

      <p>
        This page is in English, but I don't actually speak English. It would be
        great if you could contact me in Japanese.
      </p>
    </div>
  </section>
</template>

<style lang="scss" scoped>
p:not(:last-child) {
  margin-bottom: 0.5rem;
}
</style>
