// nextjs/components/TheTitle.tsx
import Image from "next/image";

interface TheTitleProps {
  className?: string;
}

export function TheTitle({ className }: TheTitleProps) {
  return (
    <div className={className}>
      <header className="flex">
        <Image
          src="/icon.png"
          alt="Takahiro Hatanaka"
          width={80}
          height={80}
          className="rounded-full h-20"
        />
        <h1 className="flex items-center ml-4 lg:text-5xl text-4xl uppercase break-words">
          Takahiro Hatanaka
        </h1>
      </header>
    </div>
  );
}

// components/TheTitle.vue
<template>
  <div>
    <header class="flex mb-5">
      <!-- <img src="icon.png" class="rounded-full h-16" /> -->
      <!-- <h1>Takahiro Hatanaka</h1> -->
      <img src="https://placehold.jp/150x150.png" class="rounded-full h-20" />
      <h1 class="flex items-center ml-4 text-5xl uppercase text-green-600">
        aaaaaaaaaaaaa
      </h1>
    </header>
  </div>
</template>

<style lang="scss" scoped>
header {
  h1 {
    font-family: "Montserrat", sans-serif;
  }
}
</style>
