// components/TheTitle.vue
<template>
  <div>
    <header class="flex mb-5">
      <!-- <img src="icon.png" class="rounded-full h-16" /> -->
      <!-- <h1>Takahiro Hatanaka</h1> -->
      <img src="https://placehold.jp/150x150.png" class="rounded-full h-20" />
      <h1 class="flex items-center ml-4 text-5xl uppercase text-green-600">
        aaaaaaaaaaaaa
      </h1>
    </header>
  </div>
</template>

<style lang="scss" scoped>
header {
  h1 {
    font-family: "Montserrat", sans-serif;
  }
}
</style>

// src/components/the-title.tsx
import { cn } from "@/lib/utils";

type Props = {
  className?: string;
};

export function TheTitle({ className }: Props) {
  return (
    <div className={cn(className)}>
      <header className="flex">
        <img
          src="https://github.com/takahirohatanaka.png"
          className="rounded-full h-20"
          width={80}
          height={80}
          alt="Takahiro Hatanaka"
        />
        <h1 className="flex items-center ml-4 lg:text-5xl text-4xl uppercase break-words">
          Takahiro Hatanaka
        </h1>
      </header>
    </div>
  );
}
